/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2019-08-21 14:09:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/blogProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/blogProject2/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1565995938335L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Content -->\n");
      out.write("<section>\n");
      out.write("\t<header class=\"main\">\n");
      out.write("\t\t<h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryInfo.CTG_NM }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\n");
      out.write("\t</header>\n");
      out.write("\t\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t<ul class=\"pagination\">\n");
      out.write("\t\t<li><span class=\"button\">Prev</span></li>\n");
      out.write("\t\t<li><a href=\"#\" class=\"page active\">1</a></li>\n");
      out.write("\t\t<li><a href=\"#\" class=\"page\">2</a></li>\n");
      out.write("\t\t<li><a href=\"#\" class=\"page\">3</a></li>\n");
      out.write("\t\t<li><span>&hellip;</span></li>\n");
      out.write("\t\t<li><a href=\"#\" class=\"page\">8</a></li>\n");
      out.write("\t\t<li><a href=\"#\" class=\"page\">9</a></li>\n");
      out.write("\t\t<li><a href=\"#\" class=\"page\">10</a></li>\n");
      out.write("\t\t<li><a href=\"#\" class=\"button\">Next</a></li>\n");
      out.write("\t</ul>\n");
      out.write("\t<ul class=\"actions\">\n");
      out.write("\t\t<li><a href=\"#\" class=\"button\">등록</a></li>\n");
      out.write("\t</ul>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t<!-- Content -->\n");
      out.write("\t\t<h2 id=\"content\">Sample Content</h2>\n");
      out.write("\t\t<p>Praesent ac adipiscing ullamcorper semper ut amet ac risus. Lorem sapien ut odio odio nunc. Ac adipiscing nibh porttitor erat risus justo adipiscing adipiscing amet placerat accumsan. Vis. Faucibus odio magna tempus adipiscing a non. In mi primis arcu ut non accumsan vivamus ac blandit adipiscing adipiscing arcu metus praesent turpis eu ac lacinia nunc ac commodo gravida adipiscing eget accumsan ac nunc adipiscing adipiscing lorem ipsum dolor sit amet nullam veroeros adipiscing.</p>\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-6 col-12-small\">\n");
      out.write("\t\t\t\t<h3>Sem turpis amet semper</h3>\n");
      out.write("\t\t\t\t<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat commodo eu sed ante lacinia. Sapien a lorem in integer ornare praesent commodo adipiscing arcu in massa commodo lorem accumsan at odio massa ac ac. Semper adipiscing varius montes viverra nibh in adipiscing blandit tempus accumsan.</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-6 col-12-small\">\n");
      out.write("\t\t\t\t<h3>Magna odio tempus commodo</h3>\n");
      out.write("\t\t\t\t<p>In arcu accumsan arcu adipiscing accumsan orci ac. Felis id enim aliquet. Accumsan ac integer lobortis commodo ornare aliquet accumsan erat tempus amet porttitor. Ante commodo blandit adipiscing integer semper orci eget. Faucibus commodo adipiscing mi eu nullam accumsan morbi arcu ornare odio mi adipiscing nascetur lacus ac interdum morbi accumsan vis mi accumsan.</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- Break -->\n");
      out.write("\t\t\t<div class=\"col-4 col-12-medium\">\n");
      out.write("\t\t\t\t<h3>Interdum sapien gravida</h3>\n");
      out.write("\t\t\t\t<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing blandit.</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-4 col-12-medium\">\n");
      out.write("\t\t\t\t<h3>Faucibus consequat lorem</h3>\n");
      out.write("\t\t\t\t<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing blandit.</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-4 col-12-medium\">\n");
      out.write("\t\t\t\t<h3>Accumsan montes viverra</h3>\n");
      out.write("\t\t\t\t<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing blandit.</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t<hr class=\"major\" />\n");
      out.write("\n");
      out.write("\t<!-- Elements -->\n");
      out.write("\t\t<h2 id=\"elements\">Elements</h2>\n");
      out.write("\t\t<div class=\"row gtr-200\">\n");
      out.write("\t\t\t<div class=\"col-6 col-12-medium\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Text stuff -->\n");
      out.write("\t\t\t\t\t<h3>Text</h3>\n");
      out.write("\t\t\t\t\t<p>This is <b>bold</b> and this is <strong>strong</strong>. This is <i>italic</i> and this is <em>emphasized</em>.\n");
      out.write("\t\t\t\t\tThis is <sup>superscript</sup> text and this is <sub>subscript</sub> text.\n");
      out.write("\t\t\t\t\tThis is <u>underlined</u> and this is code: <code>for (;;) { ... }</code>.\n");
      out.write("\t\t\t\t\tFinally, this is a <a href=\"#\">link</a>.</p>\n");
      out.write("\t\t\t\t\t<hr />\n");
      out.write("\t\t\t\t\t<h2>Heading Level 2</h2>\n");
      out.write("\t\t\t\t\t<h3>Heading Level 3</h3>\n");
      out.write("\t\t\t\t\t<h4>Heading Level 4</h4>\n");
      out.write("\t\t\t\t\t<hr />\n");
      out.write("\t\t\t\t\t<p>Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing blandit tempus accumsan.</p>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Lists -->\n");
      out.write("\t\t\t\t\t<h3>Lists</h3>\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-6 col-12-small\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<h4>Unordered</h4>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li>Dolor etiam magna etiam.</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>Sagittis lorem eleifend.</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>Felis dolore viverra.</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<h4>Alternate</h4>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"alt\">\n");
      out.write("\t\t\t\t\t\t\t\t<li>Dolor etiam magna etiam.</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>Sagittis lorem eleifend.</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>Felis feugiat viverra.</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-6 col-12-small\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<h4>Ordered</h4>\n");
      out.write("\t\t\t\t\t\t\t<ol>\n");
      out.write("\t\t\t\t\t\t\t\t<li>Dolor etiam magna etiam.</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>Etiam vel lorem sed viverra.</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>Felis dolore viverra.</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>Dolor etiam magna etiam.</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>Etiam vel lorem sed viverra.</li>\n");
      out.write("\t\t\t\t\t\t\t\t<li>Felis dolore viverra.</li>\n");
      out.write("\t\t\t\t\t\t\t</ol>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<h4>Icons</h4>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"icons\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-twitter\"><span class=\"label\">Twitter</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-facebook-f\"><span class=\"label\">Facebook</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-instagram\"><span class=\"label\">Instagram</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-github\"><span class=\"label\">Github</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-dribbble\"><span class=\"label\">Dribbble</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"icon brands fa-tumblr\"><span class=\"label\">Tumblr</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<h4>Definition</h4>\n");
      out.write("\t\t\t\t\t<dl>\n");
      out.write("\t\t\t\t\t\t<dt>Item1</dt>\n");
      out.write("\t\t\t\t\t\t<dd>\n");
      out.write("\t\t\t\t\t\t\t<p>Lorem ipsum dolor vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent. Lorem ipsum dolor.</p>\n");
      out.write("\t\t\t\t\t\t</dd>\n");
      out.write("\t\t\t\t\t\t<dt>Item2</dt>\n");
      out.write("\t\t\t\t\t\t<dd>\n");
      out.write("\t\t\t\t\t\t\t<p>Lorem ipsum dolor vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent. Lorem ipsum dolor.</p>\n");
      out.write("\t\t\t\t\t\t</dd>\n");
      out.write("\t\t\t\t\t\t<dt>Item3</dt>\n");
      out.write("\t\t\t\t\t\t<dd>\n");
      out.write("\t\t\t\t\t\t\t<p>Lorem ipsum dolor vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent. Lorem ipsum dolor.</p>\n");
      out.write("\t\t\t\t\t\t</dd>\n");
      out.write("\t\t\t\t\t</dl>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h4>Actions</h4>\n");
      out.write("\t\t\t\t\t<ul class=\"actions\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary\">Default</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">Default</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<ul class=\"actions small\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary small\">Small</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button small\">Small</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-6 col-12-small\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"actions stacked\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary\">Default</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">Default</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-6 col-12-small\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"actions stacked\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary small\">Small</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button small\">Small</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-6 col-12-small\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"actions stacked\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary fit\">Default</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button fit\">Default</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-6 col-12-small\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"actions stacked\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary small fit\">Small</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button small fit\">Small</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h4>Pagination</h4>\n");
      out.write("\t\t\t\t\t<ul class=\"pagination\">\n");
      out.write("\t\t\t\t\t\t<li><span class=\"button disabled\">Prev</span></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"page active\">1</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"page\">2</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"page\">3</a></li>\n");
      out.write("\t\t\t\t\t\t<li><span>&hellip;</span></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"page\">8</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"page\">9</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"page\">10</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">Next</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Blockquote -->\n");
      out.write("\t\t\t\t\t<h3>Blockquote</h3>\n");
      out.write("\t\t\t\t\t<blockquote>Lorem ipsum dolor vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent. Lorem ipsum dolor. Lorem ipsum dolor vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus.</blockquote>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Table -->\n");
      out.write("\t\t\t\t\t<h3>Table</h3>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h4>Default</h4>\n");
      out.write("\t\t\t\t\t<div class=\"table-wrapper\">\n");
      out.write("\t\t\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Name</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Description</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Price</th>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Item1</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Ante turpis integer aliquet porttitor.</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>29.99</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Item2</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Vis ac commodo adipiscing arcu aliquet.</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>19.99</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Item3</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td> Morbi faucibus arcu accumsan lorem.</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>29.99</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Item4</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Vitae integer tempus condimentum.</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>19.99</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Item5</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Ante turpis integer aliquet porttitor.</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>29.99</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t\t\t<tfoot>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"2\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>100.00</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</tfoot>\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h4>Alternate</h4>\n");
      out.write("\t\t\t\t\t<div class=\"table-wrapper\">\n");
      out.write("\t\t\t\t\t\t<table class=\"alt\">\n");
      out.write("\t\t\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Name</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Description</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Price</th>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Item1</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Ante turpis integer aliquet porttitor.</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>29.99</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Item2</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Vis ac commodo adipiscing arcu aliquet.</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>19.99</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Item3</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td> Morbi faucibus arcu accumsan lorem.</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>29.99</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Item4</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Vitae integer tempus condimentum.</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>19.99</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Item5</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Ante turpis integer aliquet porttitor.</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>29.99</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t\t\t<tfoot>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"2\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>100.00</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</tfoot>\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-6 col-12-medium\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Buttons -->\n");
      out.write("\t\t\t\t\t<h3>Buttons</h3>\n");
      out.write("\t\t\t\t\t<ul class=\"actions\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary\">Primary</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">Default</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<ul class=\"actions\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button large\">Large</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">Default</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button small\">Small</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<ul class=\"actions\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary large\">Large</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary\">Default</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary small\">Small</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<ul class=\"actions fit\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary fit\">Fit</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button fit\">Fit</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<ul class=\"actions fit small\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary fit small\">Fit + Small</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button fit small\">Fit + Small</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<ul class=\"actions\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button primary icon solid fa-search\">Icon</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button icon solid fa-download\">Icon</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<ul class=\"actions\">\n");
      out.write("\t\t\t\t\t\t<li><span class=\"button primary disabled\">Primary</span></li>\n");
      out.write("\t\t\t\t\t\t<li><span class=\"button disabled\">Default</span></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Form -->\n");
      out.write("\t\t\t\t\t<h3>Form</h3>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"#\">\n");
      out.write("\t\t\t\t\t\t<div class=\"row gtr-uniform\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-6 col-12-xsmall\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"demo-name\" id=\"demo-name\" value=\"\" placeholder=\"Name\" />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-6 col-12-xsmall\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" name=\"demo-email\" id=\"demo-email\" value=\"\" placeholder=\"Email\" />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- Break -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-12\">\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"demo-category\" id=\"demo-category\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">- Category -</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">Manufacturing</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">Shipping</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">Administration</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">Human Resources</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- Break -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-4 col-12-small\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"demo-priority-low\" name=\"demo-priority\" checked>\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"demo-priority-low\">Low</label>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-4 col-12-small\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"demo-priority-normal\" name=\"demo-priority\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"demo-priority-normal\">Normal</label>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-4 col-12-small\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"demo-priority-high\" name=\"demo-priority\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"demo-priority-high\">High</label>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- Break -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-6 col-12-small\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"demo-copy\" name=\"demo-copy\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"demo-copy\">Email me a copy</label>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-6 col-12-small\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"demo-human\" name=\"demo-human\" checked>\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"demo-human\">I am a human</label>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- Break -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-12\">\n");
      out.write("\t\t\t\t\t\t\t\t<textarea name=\"demo-message\" id=\"demo-message\" placeholder=\"Enter your message\" rows=\"6\"></textarea>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- Break -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-12\">\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"actions\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input type=\"submit\" value=\"Send Message\" class=\"primary\" /></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><input type=\"reset\" value=\"Reset\" /></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Image -->\n");
      out.write("\t\t\t\t\t<h3>Image</h3>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h4>Fit</h4>\n");
      out.write("\t\t\t\t\t<span class=\"image fit\"><img src=\"images/pic11.jpg\" alt=\"\" /></span>\n");
      out.write("\t\t\t\t\t<div class=\"box alt\">\n");
      out.write("\t\t\t\t\t\t<div class=\"row gtr-50 gtr-uniform\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-4\"><span class=\"image fit\"><img src=\"images/pic01.jpg\" alt=\"\" /></span></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-4\"><span class=\"image fit\"><img src=\"images/pic02.jpg\" alt=\"\" /></span></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-4\"><span class=\"image fit\"><img src=\"images/pic03.jpg\" alt=\"\" /></span></div>\n");
      out.write("\t\t\t\t\t\t\t<!-- Break -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-4\"><span class=\"image fit\"><img src=\"images/pic03.jpg\" alt=\"\" /></span></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-4\"><span class=\"image fit\"><img src=\"images/pic01.jpg\" alt=\"\" /></span></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-4\"><span class=\"image fit\"><img src=\"images/pic02.jpg\" alt=\"\" /></span></div>\n");
      out.write("\t\t\t\t\t\t\t<!-- Break -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-4\"><span class=\"image fit\"><img src=\"images/pic02.jpg\" alt=\"\" /></span></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-4\"><span class=\"image fit\"><img src=\"images/pic03.jpg\" alt=\"\" /></span></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-4\"><span class=\"image fit\"><img src=\"images/pic01.jpg\" alt=\"\" /></span></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h4>Left &amp; Right</h4>\n");
      out.write("\t\t\t\t\t<p><span class=\"image left\"><img src=\"images/pic01.jpg\" alt=\"\" /></span>Lorem ipsum dolor sit accumsan interdum nisi, quis tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent.</p>\n");
      out.write("\t\t\t\t\t<p><span class=\"image right\"><img src=\"images/pic02.jpg\" alt=\"\" /></span>Lorem ipsum dolor sit accumsan interdum nisi, quis tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent.</p>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Box -->\n");
      out.write("\t\t\t\t\t<h3>Box</h3>\n");
      out.write("\t\t\t\t\t<div class=\"box\">\n");
      out.write("\t\t\t\t\t\t<p>Felis sagittis eget tempus primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent tincidunt felis sagittis eget. tempus euismod. Magna sed etiam ante ipsum primis in faucibus vestibulum.</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Preformatted Code -->\n");
      out.write("\t\t\t\t\t<h3>Preformatted</h3>\n");
      out.write("\t\t\t\t\t<pre><code>i = 0;\n");
      out.write("\n");
      out.write("while (!deck.isInOrder()) {\n");
      out.write("    print 'Iteration ' + i;\n");
      out.write("    deck.shuffle();\n");
      out.write("    i++;\n");
      out.write("}\n");
      out.write("\n");
      out.write("print 'It took ' + i + ' iterations to sort the deck.';\n");
      out.write("</code></pre>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("</section>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/board/boardList.jsp(11,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty boardList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\n");
        out.write("\t\t<div class=\"table-wrapper\">\n");
        out.write("\t\t\t<table>\n");
        out.write("\t\t\t\t<colgroup>\n");
        out.write("\t\t\t\t\t<col width=\"10%\" />\n");
        out.write("\t\t\t\t\t<col width=\"10%\" />\n");
        out.write("\t\t\t\t\t<col width=\"60%\" />\n");
        out.write("\t\t\t\t\t<col width=\"10%\" />\n");
        out.write("\t\t\t\t\t<col width=\"10%\" />\n");
        out.write("\t\t\t\t</colgroup>\n");
        out.write("\t\t\t\t<thead>\n");
        out.write("\t\t\t\t\t<tr>\n");
        out.write("\t\t\t\t\t\t<th>No</th>\n");
        out.write("\t\t\t\t\t\t<th>제목</th>\n");
        out.write("\t\t\t\t\t\t<th>등록일</th>\n");
        out.write("\t\t\t\t\t\t<th>조회수</th>\n");
        out.write("\t\t\t\t\t</tr>\n");
        out.write("\t\t\t\t</thead>\n");
        out.write("\t\t\t\t<tbody>\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t\t</tbody>\n");
        out.write("\t\t\t</table>\n");
        out.write("\t\t</div>\n");
        out.write("\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/views/board/boardList.jsp(31,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("boardInfo");
    // /WEB-INF/views/board/boardList.jsp(31,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/boardList.jsp(31,5) '${boardList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${boardList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/board/boardList.jsp(31,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVarStatus("i");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\n");
          out.write("\t\t\t\t\t\t<tr>\n");
          out.write("\t\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardInfo.RN}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("\t\t\t\t\t\t\t<td><a href=\"/main/profile\">(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardInfo.CTG_NM}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(") &nbsp;&nbsp;&nbsp;");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardInfo.BRD_TITLE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></td>\n");
          out.write("\t\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardInfo.REG_DT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"</td>\n");
          out.write("\t\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardInfo.VIEW_CNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("\t\t\t\t\t\t</tr>\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
